### ISSUE TITLE
[BUG] read_redcap Checkbox Example Not Working

### ISSUE THREAD

**Issue by rsh52** [CHOP-CGTInformatics/REDCapTidieR#105]
# Expected Behavior
> The following is resultant of meeting with Will on 2022-12-08

Checkboxes should be exported from REDCap appropriately.

# Current Behavior
When testing with Will's example checkbox database, checkbox exports did not come out as expected: 

https://github.com/OuhscBbmc/REDCapR/blob/main/inst/misc/example.credentials#L36

**Screenshots**
In the image below, only two checkbox variables exist (`checkbox_one___1`, `checkbox_two___a`), though there are multiple options for each of these in the REDCap client side UI.

![image](https://user-images.githubusercontent.com/38384694/206557745-6e1d1a43-1c66-45e0-87e9-070941325bc5.png)

### Checklist
Before submitting this issue, please check and verify below that the submission meets the below criteria:

- [x] The issue is atomic
- [x] The issue description is documented
- [x] The issue title describes the problem succinctly
- [ ] Developers are assigned to the issue
- [x] Labels are assigned to the issue

**Comment by skadauke** [comment]
I think the culprit is line 104 in `utils.R`, in `parse_labels()`:

```r
    strsplit(" \\| ") # Split by "|"
```

We're splitting by pipes *surrounded by blanks*. Here is what the `select_choices_or_calculations` column are for the field in question:

```
1, one|2, two|3, three|4, four
a, A|b, B|c, C|d, D|e, E
```

No spaces! I think the fix is to split by pipe (without spaces) and then remove any padding whitespaces.
