### ISSUE TITLE
[FEATURE] Implement argument checking for all exported functions with `cli`-generated messages

### ISSUE THREAD

**Issue by ezraporter** [CHOP-CGTInformatics/REDCapTidieR#109]
# Feature Request Description
We currently have a patchwork of argument checking across exported functions. In some cases the error messages are generated by `checkmate` so they don't match our `cli` messages. We should have checking on all arguments for exported functions and ensure all messages are `cli`-generated.

# Proposed Solution
Add argument checking where it's missing.

We can wrap calls to `checkmate` to still use it on the backend while generating errors with `cli`. Something like:

```r
tryCatch(
  error = function(e) cli::cli_abort(...),
  checkmate::assert_*(...)
)
```

### Checklist

- [x] The issue is atomic
- [x] The issue description is documented
- [x] The issue title describes the problem succinctly
- [ ] Developers are assigned to the issue
- [x] Labels are assigned to the issue

**Comment by skadauke** [comment]
Here's a prototype that's a bit more worked out:

```r
add_one <- function(x) {
  check_argument_is_numeric_and_finite(x)
    
  x + 1
}

check_argument_is_numeric_and_finite <- function(x) {
  
  result <- checkmate::check_numeric(x, finite = TRUE)
  
  if (result == TRUE) {
    return(TRUE)
  } else {
    cli::cli_abort(
      message = c(
        "x" = "{result}",
        "i" = "The argument that was provided is `{x}`"
      )
    )
  }
}
```

**Comment by ezraporter** [comment]
What do we think about argument checking for things like `tbls` in `extract_tibbles()` that take unevaluated expressions? I'm not sure there's much checking we can do since anything can be captured as an unevaluated expression.

cc: @skadauke @rsh52
