### ISSUE TITLE
[FEATURE] Guess_Max argument

### ISSUE THREAD

**Issue by matthieu-faron** [CHOP-CGTInformatics/REDCapTidieR#141]
Dear devellopers, thanks for the amazing job on this package !

# Feature Request Description
In our databse, some columns with a large number of missing values in the first rows creates parsing error.
The problems seems to originate from the call to readr::read_csv() inside the REDCapR::redcap_read_oneshot() function.

The automatic guessing of column type by readr::read_csv based is based by default on the first 1000 rows  and may fail is there is very few non-missing values in those rows. This creates parsing problems and the data are lost.

# Proposed Solution
REDCapR::redcap_read_oneshot() has a guess_max argument which is passed to readr::read_csv

Raising the value of guess_max to higher value in REDCapR::redcap_read_oneshot() solved the parsing value on our database

## First proposition 
Add a guess_max argument to read_redcap() that will be passed to REDCapR::redcap_read_oneshot()

## Alternative proposition
Add an ellipsis argument to read_redcap() so that any argument of REDCapR::redcap_read_oneshot() can manually be passed

Thanks again !

**Comment by skadauke** [comment]
Thanks for the kind words @matthieu-faron! I don't think we'll want to add a `...` argument as this will potentially lead to all sorts of problems. But we could pass `guess_max` specifically.

@rsh52, #106 is related and we should look into whether this might be an alternative/better solution.

**Comment by rsh52** [comment]
I think this begins to open up how many additional parameters we want to support versus patching one a time with specificity, in case more requests like this come in. What if we added a "`add_redcapr_args`" param that could take the place of a `...` as a list, as it only targets the `REDCapR` sub functions we use? Could even be that we add support for a few arguments at a time and document which ones are available.

**Comment by rsh52** [comment]
@matthieu-faron Would it be possible to share your `sessionInfo` when you encounter this error? We will likely be exposing the `guess_max` argument as suggested, but I would like to reproduce your error first.

In using a dummy database with 1500 rows and empty data before the 1001st row, I wasn't able to achieve the same behavior.

Thank you!

**Comment by matthieu-faron** [comment]
Thanks !

This is my `sessionInfo()` :

```
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.utf8  LC_CTYPE=French_France.utf8    LC_MONETARY=French_France.utf8 LC_NUMERIC=C                   LC_TIME=French_France.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] lubridate_1.9.2    forcats_1.0.0      stringr_1.5.0      dplyr_1.1.1        purrr_1.0.1        readr_2.1.4        tidyr_1.3.0        tibble_3.2.1       ggplot2_3.4.1      tidyverse_2.0.0    REDCapR_1.1.0     
[12] REDCapTidieR_0.3.0

loaded via a namespace (and not attached):
 [1] pillar_1.9.0      compiler_4.2.0    lobstr_1.1.2      tools_4.2.0       bit_4.0.5         digest_0.6.31     timechange_0.2.0  gtable_0.3.3      jsonlite_1.8.4    evaluate_0.20     lifecycle_1.0.3   checkmate_2.1.0  
[13] pkgconfig_2.0.3   rlang_1.1.0       cli_3.6.0         rstudioapi_0.14   parallel_4.2.0    curl_5.0.0        xfun_0.37         fastmap_1.1.1     withr_2.5.0       httr_1.4.5        knitr_1.42        hms_1.1.3        
[25] generics_0.1.3    vctrs_0.6.1       htmlwidgets_1.6.2 grid_4.2.0        bit64_4.0.5       tidyselect_1.2.0  glue_1.6.2        R6_2.5.1          fansi_1.0.4       vroom_1.6.1       rmarkdown_2.20    tzdb_0.3.0       
[37] magrittr_2.0.3    scales_1.2.1      backports_1.4.1   htmltools_0.5.4   colorspace_2.1-0  formattable_0.2.1 utf8_1.2.3        stringi_1.7.12    munsell_0.5.0     crayon_1.5.2     
```


And this is what I get when I run `vroom::problems()` on the data frame produced by `readr::read_csv()` inside the `REDCapR::redcap_read_oneshot()`  function around line 97:


```
     row   col expected           actual
   <int> <int> <chr>              <chr>               
 1   532   222 1/0/T/F/TRUE/FALSE "Prélèvement pulmonaire" 
 2   573    53 1/0/T/F/TRUE/FALSE "2017-07-07"
 3  1015   222 1/0/T/F/TRUE/FALSE "aucune"
 4  1038   335 1/0/T/F/TRUE/FALSE "FOLFOX"
 5  1077    87 a double           "T1N0M0" 
 6  1080   341 1/0/T/F/TRUE/FALSE "audition diminuée à droite" 
 7  1257   149 a double           "01-12-2006" 
 8  2196    79 1/0/T/F/TRUE/FALSE "SIADH paranéoplasique"   
 9  2248    87 a double           "TxN1M1c" 
10  2760    53 1/0/T/F/TRUE/FALSE "2016-12-01"  
11  2857   282 1/0/T/F/TRUE/FALSE "16" 
12  3104   341 1/0/T/F/TRUE/FALSE "Toxicité Hématologique"     
13  3136   158 a double           "1-10-2020"   
14  3293    87 a double           "3A"                             
15  3392   282 1/0/T/F/TRUE/FALSE "6"                         
16  3583    87 a double           "2b"                      
```

It seems that column containing no or very few data on the 1000 first lines are guessed as logical or double. If in fact they contain date or factors the problem occurs.
No more problems if I run with a greater guessmax argument.

Thanks again !

**Comment by rsh52** [comment]
@matthieu-faron I implemented a `guess_max` argument in the dev version on `main`. I wasn't able to replicate your issue in my test database, but it would be super helpful if you could try the dev version on your end and let us know if this solves your issue.

Thank you!

**Comment by matthieu-faron** [comment]
Hi, 
I installed the dev version and it solved all the warnings. The importation is working perfectly fine now !

Thank you so much !

**Comment by rsh52** [comment]
> Hi, I installed the dev version and it solved all the warnings. The importation is working perfectly fine now !
> 
> Thank you so much !

Fantastic! Thank you for the update and bringing it our attention.
