### ISSUE TITLE
[FEATURE] REDCapTidieR v0.5 Wish List 

### ISSUE THREAD

**Issue by rsh52** [CHOP-CGTInformatics/REDCapTidieR#158]
# Feature Request Description

### Definitely include in 0.5 (September 2023)
- Error checking for make_labelled(format_labels = …) should include checking that user didn’t pass a function with parens.
   - Look at other functions. Do we check all args of all exported functions?
   - Add functions to extract metadata: extract_metadata_tibble() and extract_metadata_tibbles()
      - Would be useful to have an option to extract all metadata tibbles into one tibble				
      - I don’t think bind_metadata_tibbles() is such a good idea
   - drop_labels() 
      - Useful if you use a labelled table but then want to pipe data into a function that doesn’t like labels. Similar to tidyREDCap::drop_label()
   - Add `complete_pct` column to supertibble
      - At least a superficial check that REDCapTidieR works well with REDCap multi-language management-enabled projects
						
### Possibly include in 0.5, maybe later
- Codebooks ~ in collaboration with Ray Balise: write_codebook_html(), write_codebook_word(), write_codebook_md()
   - Write a publication-quality codebook
   - Should support skimr
- Write separate function to extract REDCap project info (`read_redcap_project_info()`)?
   - One row per tibble
   - Should support “big dumb box” parsing from YAML
   - Extract log into `redcap_log`. This should be off by default. 
   - Extract users into `redcap_users`. This should probably be off by default.
   - Extract dags into `redcap_dags`. Should be on or off by default? Can we detect if DAGs are on?

### Checklist

- [NA] The issue is atomic
- [ ] The issue description is documented
- [ ] The issue title describes the problem succinctly
- [ ] Developers are assigned to the issue
- [ ] Labels are assigned to the issue

**Comment by JanMarvin** [comment]
* Some tests require packages from suggest (`labelled`,` httptest`, and `skimr`). Maybe you could add something like `skip_if_not_installed()` for these? I ran a revdep and it failed due to these packages missing.

**Comment by rsh52** [comment]
> * Some tests require packages from suggest (`labelled`,` httptest`, and `skimr`). Maybe you could add something like `skip_if_not_installed()` for these? I ran a revdep and it failed due to these packages missing. [Edit:] probably `openxlsx2` as well. I only listed packages that were not already installed on my system.

Ah thank you so much for the advice and heads up! We will definitely implement this, probably within a 0.4 patch.

**Comment by skadauke** [comment]
@rsh52 and @ezraporter, can we break this issue into backlog issues? Also, maybe we can do the `complete_pct` (`form_complete_pct`?) one, should be easy, and would be nice to see the percentage of records that have the form marked as completed.

**Comment by rsh52** [comment]
New issues opened for remaining wishlist items, closing this for now.
