### ISSUE TITLE
[FEATURE] References Improvements

### ISSUE THREAD

**Issue by RhysPeploe** [CHOP-CGTInformatics/REDCapTidieR#172]
openjournals/joss-reviews/issues/6277

When checking the references on the paper, a few things came up:
- [x] line 108/109 the URL does not work, leads to a 404 error [REDCapDM](https://ubidi.github.io/REDCapDM/)
- [x] line 104 lowercase r for the programming language, suggest capitalisation
- [x] line 111 similar lowercase for redcap, suggest REDCap to be consistent
- [x] line 126 does not include the URL for the tibble package (although the link in the text line 64 works fine)
- [x] line 134 the url includes the " (website)" so that part needs unlinking from the hyperlink, as currently the url does not work

Once these are resolved my checklist for submission will be complete, thanks.

### Checklist

- [X] The issue is atomic
- [X] The issue description is documented
- [X] The issue title describes the problem succinctly
- [x] Developers are assigned to the issue
- [X] Labels are assigned to the issue

**Comment by rsh52** [comment]
Hi @RhysPeploe. Thanks for the feedback. I looked at your recommendations and have a couple of questions:

> line 108/109 the URL does not work, leads to a 404 error [REDCapDM](https://ubidi.github.io/REDCapDM/)

It seems that team moved the URL, I will update it to the new link.

> line 104 lowercase r for the programming language, suggest capitalisation
> line 111 similar lowercase for redcap, suggest REDCap to be consistent

I do not see these on my end, is there any chance something is getting lost in translation?

> line 126 does not include the URL for the tibble package (although the link in the text line 64 works fine)

Can you confirm this link works: https://tibble.tidyverse.org/
This is what is hyperlinked to the tibble package, and works on my end.

> line 134 the url includes the " (website)" so that part needs unlinking from the hyperlink, as currently the url does not work

Apologies, it is difficult for me to follow these line numbers since they are different from [what is on GitHub](https://github.com/CHOP-CGTInformatics/REDCapTidieR/blob/main/paper/paper.md?plain=1). I'm wondering if the capitalization issues you're seeing might be solved there as well. Which link is this in reference to?

**Comment by RhysPeploe** [comment]
![image](https://github.com/CHOP-CGTInformatics/REDCapTidieR/assets/68282471/0cea69db-33c3-48f8-b666-fb272c593a74)

**Comment by rsh52** [comment]
Ah thank you @RhysPeploe 

I see these are in the bib file. The first one is odd, is there a chance this is auto-enforced by the editorial bot? I have "R" capitalized in the file:

https://github.com/CHOP-CGTInformatics/REDCapTidieR/blob/78af9f881903ddd98e705bd6fe402357e13f0609/paper/paper.bib#L52-L54

For `redcapAPI` this is the actual [name of the package](https://cran.r-project.org/web/packages/redcapAPI/index.html), so IMO we should leave it in this format.

I can definitely fix the `tibble` URL citation. 👍 
I will remove the "(website)" from the `skimr` citation 👍

**Comment by RhysPeploe** [comment]
Try double parentheses {{title}}, this _should_ retain the way you have writen the title

@Manual{redcapr_cit,
  title = {{REDCapR: Interaction Between R and REDCap}},
  author = {Will Beasley},
  year = {2023},
  url = {https://ouhscbbmc.github.io/REDCapR/},
  note = {https://ouhscbbmc.github.io/REDCapR/, https://github.com/OuhscBbmc/REDCapR, https://www.ouhsc.edu/bbmc/, https://project-redcap.org},
}

My bad on the package name redcapAPI, keep that the same

**Comment by rsh52** [comment]
@RhysPeploe PR merged to `main`!

**Comment by RhysPeploe** [comment]
@rsh52 everything seems to be resolved - thanks!
