### ISSUE TITLE
[FEATURE] Add test cases for attempting to access PHI-restricted data

### ISSUE THREAD

**Issue by ezraporter** [CHOP-CGTInformatics/REDCapTidieR#38]
# Feature Request Description
REDCap has settings to restrict export of fields identified as PHI. These settings impact the content of fields returned by `REDCapR`.
![deidentified-redcap](https://user-images.githubusercontent.com/60618324/192831609-c1f5bd8d-992e-4193-bae0-e82d748a8043.png)

Our testing suite should include tests that check for expected behavior when a user attempts to access a form for which they don't have full permissions to export.

# Proposed Solution
This is an initial pass at expected behavior across a range cases. The parameters I'm varying are:
1. Whether the form was requested specifically vs. requested by default
2. Whether the user has access to all, some, or no fields in the form

| Request | Permissions within form | Proposed Behavior | `REDCapR` Behavior |
|---|---|---|---|
| `forms = NULL` (default) | All fields |  success | success, all accessible fields returned |
| `forms = NULL` (default) | Subset of fields |  warning? | success, all accessible fields returned |
| `forms = NULL` (default) | No fields | warning? | success, all accessible fields returned |
| `forms = "name_of_form"` | All fields | success | success, all accessible fields returned |
| `forms = "name_of_form"` | Subset of fields | warning? | success, all accessible fields returned |
| `forms = "name_of_form"` | No fields | warning | success, all fields in the project returned *including ones the user doesn't have access to* |

### Checklist

- [x] The issue is atomic
- [x] The issue description is documented
- [x] The issue title describes the problem succinctly
- [x] Developers are assigned to the issue
- [x] Labels are assigned to the issue

**Comment by skadauke** [comment]
Great question what the behavior should be. I'm not entirely sure. What does `REDCapR::read_redcap_oneshot()` do in each of the `forms = "name_of_form"` cases?

**Comment by ezraporter** [comment]
> Great question what the behavior should be. I'm not entirely sure. What does `REDCapR::read_redcap_oneshot()` do in each of the `forms = "name_of_form"` cases?

Looked into this yesterday and updated the table in my issue with `REDCapR`'s behavior. The theme is that `REDCapR` doesn't issue any errors or warnings and returns everything the user has access to.

The (strange) exception is if the user does `forms = "form-with-no-export-access"` in which case the REDCap API seems to return all fields in the project including ones the user doesn't have permission to access. This last case seems like a security flaw that I wonder if our redcap admins would want to know about.
