### ISSUE TITLE
[FEATURE] Implement automated lintr and styler checks

### ISSUE THREAD

**Issue by ezraporter** [CHOP-CGTInformatics/REDCapTidieR#63]
# Feature Request Description
We should have automated checked to ensure the package is lint free and follows appropriate style

# Proposed Solution
For `lintr` we can add an `expect_lint_free()` test to our testing suite. This will give us a full lint check without changing GHA workflows.

For `styler` the best solution is probably [`precommit`](https://lorenzwalthert.github.io/precommit/articles/available-hooks.html#style-files). The hook can be configured to style files automatically or just alert for failures without modifying files.

### Checklist

- [x] The issue is atomic
- [x] The issue description is documented
- [x] The issue title describes the problem succinctly
- [x] Developers are assigned to the issue
- [x] Labels are assigned to the issue

**Comment by rsh52** [comment]
## From 2022-10-31 Planning Meeting:

- Forgo `styler` for now
- Decide on what `lintr`s we want via `.lintr` config file
