### ISSUE TITLE
[FEATURE] Include event labels in `redcap_events` tibbles

### ISSUE THREAD

**Issue by ezraporter** [CHOP-CGTInformatics/REDCapTidieR#67]
# Feature Request Description
Events in longitudinal redcaps can have custom labels in addition to identifiers:

![Screen Shot 2022-11-07 at 1 26 32 PM](https://user-images.githubusercontent.com/60618324/200386850-f9e465cd-3df1-4659-bf09-23ed1c3a51d6.png)

The `redcap_events` columns of the supertibble should include these labels.

# Proposed Solution
The event labels are accessible with the Export Events API method but `REDCapR` doesn't currently have a wrapper for this. We can make an issue and supply the code. Once that's running in `REDCapR` it will be easy to add this field to `redcap_events` by modifying `link_arms()`.

### Checklist

- [x] The issue is atomic
- [x] The issue description is documented
- [x] The issue title describes the problem succinctly
- [x] Developers are assigned to the issue
- [x] Labels are assigned to the issue

**Comment by skadauke** [comment]
I would hold back on implementing this until the version of `REDCapR` that supports this is on CRAN.

**Comment by ezraporter** [comment]
Opened an issue in `REDCapR`: https://github.com/OuhscBbmc/REDCapR/issues/457

**Comment by ezraporter** [comment]
PR is open on `REDCapR`: https://github.com/OuhscBbmc/REDCapR/pull/460

**Comment by rsh52** [comment]
@ezraporter Since this was merged on `REDCapR` can we include this easily?

**Comment by ezraporter** [comment]
> Since this was merged on `REDCapR` can we include this easily?

I think we’re still waiting for the next `REDCapR` CRAN release. Right now this is only in the development version.
