### ISSUE TITLE
[BUG] `data_na_pct` returned by `read_redcap_tidy()` is between 0 and 1 as opposed to 0 and 100

### ISSUE THREAD

**Issue by ezraporter** [CHOP-CGTInformatics/REDCapTidieR#68]
# Expected Behavior
`data_na_pct` should return a true percentage between 0 and 100

# Current Behavior
`data_na_pct` is between 0 and 1

# Suggested fix

Multiply `data_na_pct` by 100 in `calc_metadata_stats()`

An alternative solution is to use `scales::percent()` to format the percentage. The downside is that `scales` functions return a string so that the user wouldn't be able to easily manipulate `data_na_pct`. I think that makes multiplying by 100 the most elegant solution.

### Checklist
Before submitting this issue, please check and verify below that the submission meets the below criteria:

- [x] The issue is atomic
- [x] The issue description is documented
- [x] The issue title describes the problem succinctly
- [x] Developers are assigned to the issue
- [x] Labels are assigned to the issue

**Comment by skadauke** [comment]
@rsh52, can you take a look at `formattable::percent`? It'll allow us to display a fraction as a percentage without converting it to a character. I think the `format = "fg"` option looks really good.

https://github.com/renkun-ken/formattable

``` r
library(formattable)
x <- c(1, 0.99, 0.9, 0.1, 0.01, 0.001, 0.0000001)
percent(x)
#> [1] 100.00% 99.00%  90.00%  10.00%  1.00%   0.10%   0.00%  
percent(x, format = "fg")
#> [1] 100%      99%      90%      10%       1%     0.1%     0.00001%
```

**Comment by rsh52** [comment]
Haha, you'll have to get @ezraporter's approval there. I had mentioned `formattable` in the past for this as well but he was apprehensive. Ezra do you remember why?

The output is similar to what we have for `lobstr` bytes.

**Comment by ezraporter** [comment]
> Haha, you'll have to get @ezraporter's approval there. I had mentioned `formattable` in the past for this as well but he was apprehensive. Ezra do you remember why?

Deep, potentially unfounded distrust of introducing non-standard data types due to getting [burned before](https://github.research.chop.edu/analytics/rocqi/issues/556).

I'm happy to be outvoted here so feel free to proceed if you both agree it's the right move. In my experience when you adopt a non-standard class you just can't guarantee it will work with an arbitrary function from another package so the benefit of adding it better really be worth it.

**Comment by skadauke** [comment]
Ah, but that's a little bit different I think. A `formattable` is still a `numeric` just with a couple of attributes slapped on and a custom S3 `print` method dispatched. Also, I would imagine people will use the percentages really only for interactive display and not as inputs into downstream computing so I think the risk of something breaking because we formatted the percentages to look nice is very low.

**Comment by ezraporter** [comment]
If we're pretty sure it's only going to be used for display purposes it's probably fine. Agree that potential issues are less likely and will be much smaller than with `integer64` but these things do add complexity that often isn't worth it in IMO.

In either case, I'd say go for it here.
