### ISSUE TITLE
[FEATURE] Throw a warning when two or more choices have the same label

### ISSUE THREAD

**Issue by skadauke** [CHOP-CGTInformatics/REDCapTidieR#89]
# Feature Request Description

When REDCapTidieR detects that a multiple choice field `radio`, `dropdown`, or `checkbox` has two or more choices where the choice label is the same it should throw a warning.

REDCap allows multiple choices to have the same label (not the same raw value) but this is probably always an error. 
REDCapTidieR converts the choice values to the levels of a factor, ignoring the raw value. When a factor is generated in which multiple levels have the same label, those levels are automatically combined into one level. 

### Checklist

- [x] The issue is atomic
- [x] The issue description is documented
- [x] The issue title describes the problem succinctly
- [x] Developers are assigned to the issue
- [x] Labels are assigned to the issue

**Comment by ezraporter** [comment]
Rather than simply combining levels, `REDCapTidieR` fails in these cases with the unhelpful error:
```r
Error in `levels<-`(`*tmp*`, value = as.character(levels)) : 
  factor level [2] is duplicated
```

This is because we explicitly assign the levels here:

https://github.com/CHOP-CGTInformatics/REDCapTidieR/blob/26faf827d6beeee9e2a6afa58e838809e92ee760/R/utils.R#L419

```r
factor("a", levels = c("a", "a"))

#> Error in `levels<-`(`*tmp*`, value = as.character(levels)) : 
#>   factor level [2] is duplicated
```

@skadauke @rsh52 should we upgrade this to issues to `bug` since it causes `read_redcap()` to fail?

If we don't want to actually implement the warning now a quick fix is just to switch the code above to `factor(levels = unique(parse_labels_output))`. That would get us back to the behavior @skadauke describes in the issue description.

**Comment by rsh52** [comment]
I think this warrants bumping up to bug 🐞 status. 

My opinion is to implement the `unique` fix, and prior to implement a `cli` check once `parse_labels_output` is defined to check for `duplicated` values and return any detected.

Maybe something like below? If I'm interpreting today's issue correctly.

```r
string <- "1, A | 2, B | 3, C | 4, B"

parse_labels_output <- parse_labels(string, return_vector = T)
parse_labels_output

field_name <- "duplicate_labels"

if (any(duplicated(parse_labels_output))) {
  msg <- paste(
    "Duplicate label{?s} detected for var `{field_name}`: ",
    parse_labels_output[duplicated(parse_labels_output)],
    ".", sep = ""
  )
  cli_warn(
    c("!" = msg)
  )
}

> Warning message:
! Duplicate label detected for var `duplicate_labels`: B. 
```

**Comment by ezraporter** [comment]
I'm planning to spend some time on `REDCapTidieR` tomorrow so I'll at least do the `unique()` fix and if it's simple enough can implement the warning as well

**Comment by skadauke** [comment]
> I'm planning to spend some time on `REDCapTidieR` tomorrow so I'll at least do the `unique()` fix and if it's simple enough can implement the warning as well

I like this solution. Let's make sure that the warning message is super easy to understand and makes it easy for the user to fix the issue.
