### ISSUE TITLE
Consider removing the "experimental" lifecycle badge

### ISSUE THREAD

**Issue by skadauke** [CHOP-CGTInformatics/REDCapTidieR#94]
The API cleanup, document revisions, and performance improvements for 0.2 leave the package in a state that I feel are ready to be shared publicly. Take a look [here](https://lifecycle.r-lib.org/articles/stages.html) and let me know if you agree.

**Comment by rsh52** [comment]
Based on definitions for experimental/stable I think we're nearing "stable." I'm hesitant to bump this until we've had 0.2 out for a reasonable time and are happy with the function name changes and don't foresee making any more. I didn't see anything saying we have to coincide badges with releases, so we could always update it later.

**Comment by ezraporter** [comment]
It doesn't seem like a bad idea to give ourselves (and others) a little experience with 0.2 before bumping it. I agree we're really close but the pace at which we've found bugs by messing with the package makes it feel not quite stable yet to me. A useful checkpoint might be what we find as the Prodigy dashboard is developed. If that ends up being a breeze from the `REDCapTidieR` side I'll feel different.

**Comment by skadauke** [comment]
Looks like we might introduce a bunch of additional API changes in 0.3 (to enable more tidyselecting) so let's hold off for now.
